### ISSUE TITLE
Niai breaks Tampermonkey Scripts

### ISSUE THREAD

**Issue by mwil** [mwil/wanikani-userscripts#2]
_Originally posted by @Koolstr in https://github.com/mwil/wanikani-userscripts/issues/1#issuecomment-431503772_

**Comment by mwil** [comment]
Interesting, I didn't use the feature that broke Keisei there. I will check it out.

I added support for the Wanikani Open Framework a few weeks ago to show which items are really unlocked to Niai, but it should be fully optional. To find where the problem is, do you have WKOF installed?

**Comment by Koolstr** [comment]
I don't know if you changed something, but it is working now. Both Keisei and Niai work, with and without WKOF.
I've had WKOF installed and activated for quite some time now, though it is interesting to consider that it may have had something to do with that.

**Comment by mwil** [comment]
Thanks for the feedback, I was checking what could have been the cause, but except for the WKOF some time ago I didn't change anything yet. I didn't receive reports in the WK forums from other people, maybe it was something that got updated by Firefox or Tampermonkey. 

I will check further if there are some hidden problems with my WKOF integration.

**Comment by Koolstr** [comment]
This issue has returned, for me. Both Keisei and Niai (run separately or together) keep all Firefox Tampermonkey extensions from running, themselves included. Please look into what has changed.
