### ISSUE TITLE
Niai: Broken menu after Wanikani removed FontAwesome

### ISSUE THREAD

**Issue by gunt3001** [mwil/wanikani-userscripts#29]
### Description

About 2 weeks ago Wanikani had a major update to its font and icons handling. Part of that involved [using SVG icons instead of font-awesome](https://community.wanikani.com/t/wanikani-icons-update/65197) on Wanikani platform.

This seem to break Niai's menu bar (and perhaps other places) that relies on FontAwesome for icons.

### Environment

- Firefox 123.0.1 (64-bit)
- Tampermonkey 5.1.0
- Wanikani Niai Similar Kanji 1.3.37

### Screenshot 

![image](https://github.com/mwil/wanikani-userscripts/assets/5871589/891ee345-7c9a-4faa-a163-cd5ff3a783e0)

**Comment by lupomikti** [comment]
The fix for this has just been merged. Sorry I'm a github noob or else I might have been able to make it so merging the PR closes this issue automatically.
